import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    appicon:{
        width:150,
        height:150,
        alignSelf:'center',
        marginTop:60
    },
    title:{
        marginTop:40,
        marginLeft:20
    },
    txt:{
        color:'gray',
        fontWeight:'bold',
        fontSize:18
    },
    titleinput:{
        marginTop:5,
        width:380,
        borderWidth:2,
        borderColor:'#b2b3b3',
    },
    description:{
        marginTop:10,
        marginLeft:20
    },
    savebtn:{
        width:120,
        height:50,
        borderRadius:70,
        backgroundColor:'#5ba1f4'
    },
    txtbtn:{
        color:'white',
        textAlign:"center",
        fontWeight:'bold',
        fontSize:18,
        marginTop:10
    },
    canclebtn:{
        
        width:120,
        height:50,
        borderRadius:70,
        backgroundColor:'#5ba1f4'
    }
});