import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    header:{
        width:'100%',
        height:50,
        backgroundColor:'white'
    },
    logo:{
        width:30,
        height:30,
        marginTop:5,
        marginLeft:20
    },
    projectname:{
        color:'#5ba1f4',
        marginTop:5,
        marginLeft:10,
        fontWeight:'bold'
    },
    search:{
        marginLeft:200
    },
    flatlistItem:{
        marginTop:15,
    },
    flatlistImage:{
        alignSelf:"center",
        width:'99.5%',
        // width:375,
        height:215,
        // marginTop:10,
        resizeMode:"cover"
    },
    horizontalflatlistitem:
    {
        width:200,
        height:50,
        borderRadius:70,
        marginHorizontal:5,
        backgroundColor:'#ECECEC',
        marginTop:5
    },
    subjecttxt:{
        color:'black',
        fontWeight:"bold",
        textAlign:'center',
        marginTop:10,
        numberOfLines:1,
        ellipsizeMode:'tail',
        paddingHorizontal:8
    },
    course:{
        width:150,
        height:50,
        borderRadius:5,
        marginHorizontal:5,
        backgroundColor:'#5ba1f3',
        marginTop:5,
    },
    coursetxt:{
        color:'black',
        fontWeight:"bold",
        textAlign:'center',
        marginTop:12,
        fontSize:20
    },
    itemdetailsContainer:{
        alignSelf:"center",
        width:"99%",
        backgroundColor:"white",
        elevation:5,
        shadowColor: 'black',
        borderBottomLeftRadius:10,
        borderBottomRightRadius:10,
        height:80
    }
});
